apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: dbconfigs.api.jtthink.com
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: api.jtthink.com
  # 列举此 CustomResourceDefinition 所支持的版本
  versions:
    - name: v1
      # 是否有效
      served: true
      storage: true
      # 新增kb get dc 响应字段 没有值是因为还控制器中操作提供值
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.ready
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  # minimum: 1  # 规则：最小值是1
                  # maximum: 5 # 规则：最大5个
                  default: 1  # 默认
                dsn:
                  type: string
              required: # 必须要有的字段
                - dsn
            status: # 子资源
              type: object
              properties:
                replicas:
                  type: integer  #最终状态副本数
                ready:
                  type: string

      subresources: # 启动子资源
        status: { } # 启动了上面定义的status字段内容
        scale: # 扩容属性
          specReplicasPath: .spec.replicas    #期望副本数
          statusReplicasPath: .status.replicas  #最终副本数

  # 范围是属于namespace的 ,可以是 Namespaced 或 Cluster
  scope: Namespaced
  names:
    # 复数名
    plural: dbconfigs
    # 单数名
    singular: dbconfig
    # 类型名
    kind: DbConfig
    listKind: DbConfigList
    # kind的简称，就像service的简称是svc
    shortNames:
      - dc